version: '3.4'

services:
  db:
    image: docker-from-zero-to-mastery-dotnet-8-db
    command: mysqld --default-authentication-plugin=caching_sha2_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker_from_zero_to_mastery_dotnet
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    # volumes:
    #   - ./data1:/var/lib/mysql
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - dev2-network

  docker-from-zero-to-mastery-dotnet-8:
    image: docker-from-zero-to-mastery-dotnet-8
    build:
      context: .
      dockerfile: DockerFromZeroToMastery-ASP.NET-8/Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MySQLConnection__MySQLConnectionString: "Server=db;Port=3308;DataBase=docker_from_zero_to_mastery_dotnet;Uid=docker;Pwd=docker"
    ports:
      - 4430:8080
      - 44300:8081
    depends_on:
      - db
    networks:
      - dev2-network

networks:
  dev2-network:
    driver: bridge